### PR TITLE
Added PHP 8.2.8 for Mac x64 and x86

### PR DESCRIPTION
**Pull request by vitorleonel**
Hi,

### Update version

I've updated the version to be the same as @kalizi did in its PR, so we have Linux and Mac in the same version.

### Fixed an error to build x64 on Mac

I tried to build my test application and I had an error saying that it was impossible to copy php from the x64 folder, so I created this folder.

image

### Extensions

The extensions are the same (php -v):

```
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
openssl
pcre
PDO
pdo_sqlite
random
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
zlib
```

Note: I also used `static-php-cli` to build the binary.

### CODE REVIEW

**Comment by kalizi** [comment]
> I find it concerning in terms of security that the binaries aren't being built by the CI and anyone can just submit them in a PR. People can secretly include anything in them, how would one know?

You're right, binaries should be built using CI but as you can see from the NativePHP website, this is still an alpha version and there's a significant path to improvements! 

One PR at a time ;)

**Comment by pintend** [comment]
github ci wont be able to compile for m1/m2 https://beyondco.de/blog/announcing-laravel-herd#:~:text=Why%20a%20self%2Dhosted%20GitHub%20action%20runner

**Comment by osbre** [comment]
@pintend then other CI tool would

**Comment by simonhamp** [comment]
New official binaries are coming. We won't be accepting binaries submitted by the community.

**Pull request closed without merging**
