### PR TITLE
Added PHP 8.2.8 for Linux x64

### PR DESCRIPTION
**Pull request by kalizi**
Hi, as in the title, I added the binary for Linux x64 and tested it on Fedora Linux 38!

### CODE REVIEW

**Comment by simonhamp** [comment]
Could you describe how you've built this executable?

Which extensions are included?

**Comment by kalizi** [comment]
Sure, as in the issue https://github.com/NativePHP/php-bin/issues/2  I got the prebuilt binary from https://github.com/crazywhalecc/static-php-cli 

The extensions contained (as reported from the doc are): 
`bcmath,bz2,calendar,ctype,curl,dom,exif,fileinfo,filter,ftp,gd,gmp,iconv,xml,mbstring,mbregex,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,redis,session,simplexml,soap,sockets,sqlite3,tokenizer,xmlwriter,xmlreader,zlib,zip`

Anyway to be sure, running `./php -m` I get the following output: 
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gmp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
redis
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

```

**Comment by mpociot** [comment]
@kalizi thank you for the PR!
We currently use a trimmed down list of dependencies for the macOS builds in order to keep the binary smaller.

```
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
openssl
pcre
PDO
pdo_sqlite
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
zlib
```

I think it makes sense to use the exact same set of extensions for Linux as well, so that we don't run into any cross-compilation issues.
Of course we can always rebuild the binaries and enable more extensions later on 👍 

Could you rebuild the binary with only these extensions enabled?

**Comment by kalizi** [comment]
Sure, should I open another PR to avoid embedding this binary into the commit tree?

**Comment by kalizi** [comment]
I rebuilt it with the libs you provided, the current `php -m` is 

```
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
openssl
pcre
PDO
pdo_sqlite
random
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
zlib
```

**Comment by mpociot** [comment]
Great, thank you!

**Pull request merged**
